name: Get AWS Session Token

on:
  workflow_dispatch:
  # Add other events or triggers as needed

jobs:
  get-session-token:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-1  # Change to your desired AWS region

    - name: Get AWS Session Token
      run: |
        # Replace ROLE_ARN with the ARN of the IAM role you want to assume
        role_arn=arn:aws:iam::600764632321:role/MyPipelineTrustPolicyRole
        session_name="GitHubActionsSession"
        
        sts_response=$(aws sts assume-role --role-arn $role_arn --role-session-name $session_name)

        access_key=$(echo $sts_response | jq -r .Credentials.AccessKeyId)
        secret_key=$(echo $sts_response | jq -r .Credentials.SecretAccessKey)
        session_token=$(echo $sts_response | jq -r .Credentials.SessionToken)

        echo "::set-secret name=AWS_SESSION_TOKEN::$session_token"
        echo "::set-secret name=AWS_ACCESS_KEY_ID::$access_key"
        echo "::set-secret name=AWS_SECRET_ACCESS_KEY::$secret_key"
      env:
        AWS_DEFAULT_REGION: us-east-1  # Change to your desired AWS region
