name: Deploy Resources with Terraform

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the deployment on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
        aws-region: us-east-1  # Change this to your desired AWS region

    - name: Run Terraform
      run: |
        cd path/to/your/terraform/directory  # Change to the directory where your Terraform configuration files are located
        terraform init
        terraform apply -auto-approve

    - name: Cleanup
      run: |
        cd path/to/your/terraform/directory
        terraform destroy -auto-approve
